changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
        - "semver:major"
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
        - "semver:minor"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Maintenance"
      labels:
        - "*"
